@startuml

entity dictionary {
    id
    url
    title
    memo
}

entity tag {
    id
    dictionary_id
    name
}

' --------------------------------------------------
' crawl data
' --------------------------------------------------
entity page {
    id
    dictionary_id
    title
    url
}

entity page_attribute {
    id
    page_id
    key
    value
    type
}


' --------------------------------------------------
' crawl query
' --------------------------------------------------
entity crawl_root_doc {
    id
    dictionary_id
    list_page_path
    list_holder_query
    list_item_query
    ins_at
    upd_at
    del_at
}

entity crawl_query {
    id
    crawl_root_doc_id
    name
    query
}

entity crawl_source {
    id
    crawl_root_doc_id
    url
    insertedAt
    updatedAt
    deletedAt
}

dictionary "1" *--  "0..n" tag
dictionary "1" *-- "1..n" page
page o-- page_attribute
dictionary "1" *-- "1" crawl_root_doc
crawl_root_doc o-- crawl_source
crawl_root_doc o-- crawl_query

@enduml