spring:
  output.ansi.enabled: always
  integration:
    poller:
      fixed-delay: 1000
  cloud:
    stream:
      bindings:
        input:
        carbon_crawl_target_source:
          destination: crawl.target
          contentType: application/json
        carbon_crawl_target_sink:
          destination: crawl.target
          contentType: application/json
          group: g.crawl.target
      kafka:
        binder:
          brokers:
          - kafka.carbon-crawler.internal:9092
rdb:
  main:
    url: jdbc:mysql://rdb.carbon-crawler.local:43306/crawler_definition
    username: carbon
    password: carbonpw
    option:
      useSSL: false

driver:
  hub:
    url: http://driver.carbon-crawler.local:4444/wd/hub

logging.level.: info
