version: '3'
services:
  main_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crawlerdb
      MYSQL_USER: carbon
      MYSQL_PASSWORD: carbonpw
    ports:
    - "40003:3306"
    volumes:
    - ./mysql_conf:/etc/mysql/conf.d
  db_migration:
    image: boxfuse/flyway:5.1
    command: clean migrate
    volumes:
    - ./flyway_conf/conf:/flyway/conf
    - ../carbon-crawler-model/schema/sql:/flyway/sql
    depends_on:
    - main_db
  schemaspy:
    image: schemaspy/schemaspy:6.0.0
    volumes:
    - ../carbon-crawler-model/schema/er:/output
    command:
    - -t
    - mysql
    - -db
    - crawlerdb
    - -s
    - crawlerdb
    - -host
    - main_db:3306
    - -u
    - carbon
    - -p
    - carbonpw
    depends_on:
    - main_db
  selenium_hub:
    image: selenium/hub:3.13.0-argon
    ports:
    - "4444:4444"
    environment:
      GRID_BROWSER_TIMEOUT: 30
  chrome_node:
    image: selenium/node-chrome:3.13.0-argon
    depends_on:
    - selenium_hub
    environment:
      HUB_HOST: selenium_hub
      HUB_PORT: 4444
  firefox_node:
    image: selenium/node-firefox:3.13.0-argon
    depends_on:
    - selenium_hub
    environment:
      HUB_HOST: selenium_hub
      HUB_PORT: 4444
  # ==================================================
  # kafka Orchestration
  # ==================================================
  # pause for network host
  # see also
  # - https://github.com/wurstmeister/kafka-docker/wiki/Connectivity
  # - https://davidfrancoeur.com/post/kafka-on-docker-for-mac/
  # ------------------------------
  # for test compose-network(outside of pause-network)
  #  kafkacat:
  #    image: solsson/kafkacat
  #  trifecta:
  #    image: janschultecom/docker-trifecta
  #    ports:
  #    - 9001:9000
  #    environment:
  #      ZK_HOST: pause:2181
  #    depends_on:
  #    - kafka_root
  #    - kafka_node
  #  kafka_manager:
  #    build: ./kafka_manager
  #    ports:
  #    - "9000:9000"
  #    volumes:
  #    # for cache, caz sbt dependency resolution take sooooo much time
  #    - ./kafka_manager/build:/opt/kafka_manager
  #    - ~/.sbt:/root/.sbt
  #    - ~/.ivy2:/root/.ivy2
  #    depends_on:
  #    - kafka_root
  #    - kafka_node
  #    environment:
  #      ZK_HOSTS: pause:2181
  # ------------------------------
  pause:
    image: gcr.io/google-containers/pause:3.1
    ports:
    - 2181:2181
    - 9092-9102:9092-9102
  zookeeper:
    image: zookeeper:3.4
    pid: service:pause
    network_mode: service:pause
    depends_on:
    - pause
  kafka_root:
    image: wurstmeister/kafka:2.11-2.0.0
    environment:
      HOSTNAME_COMMAND: 'echo pause'
      PORT_COMMAND: 'echo 9092'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:_{PORT_COMMAND}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:_{PORT_COMMAND}
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    pid: service:pause
    network_mode: service:pause
    depends_on:
    - zookeeper
  kafka_node:
    image: wurstmeister/kafka:2.11-2.0.0
    # -v docker.sock
    # only for local, it is very !!dangerous!!
    # local convenience for detecting free port
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOSTNAME_COMMAND: 'echo pause'
      # find free port by diff using port vs docker port
      PORT_COMMAND: "diff <(netstat -tl | awk 'NR>2 {print $$4}' | cut -d: -f2 | sort) <(hostname | xargs -IHOST docker port HOST  | cut -d: -f2 | sort) | grep -E '^\\+[0-9]' | shuf | head -n1 | cut -d+ -f2"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:_{PORT_COMMAND}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:_{PORT_COMMAND}
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      # TODO: JMX is not available... due to Competing port
      # KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099"
      # JMX_PORT: 1099
    pid: service:pause
    network_mode: service:pause
    depends_on:
    - kafka_root
  dataflow:
    image: springcloud/spring-cloud-dataflow-server-local:1.6.1.RELEASE
    volumes:
    # making dataflow be able to access host's maven repository via maven:// schema
    - ~/.m2:/root/.m2
    ports:
    - "9393:9393"
    environment:
    - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers=pause:9092
    depends_on:
    - zookeeper
    - kafka_root
