version: '3'
services:
  # https://tools.ietf.org/html/rfc952
  # follow domain specification
  config.carbon.local:
    build:
      context: ../carbon-cloud/config/server
      args:
        JAR_FILE: ./build/libs/server-1.0.0-SNAPSHOT.jar
    ports:
      - "40000:80"
  rdb.carbon.local:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crawlerdb
      MYSQL_USER: carbon
      MYSQL_PASSWORD: carbonpw
    ports:
      - "40003:3306"
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d
  db_migration:
    image: boxfuse/flyway:5.2.1
    command: clean migrate
    volumes:
      - ./flyway_conf/conf:/flyway/conf
      - ../carbon-crawler-model/schema/sql:/flyway/sql
    depends_on:
      - rdb.carbon.local
  pubsub.carbon.local:
    build:
      context: ./gcp_pubsub
    volumes:
      - ../secrets/gcp/certs:/certs
    environment:
      KEY_FILE: /certs/pubsub_svc.json
      PROJECT_ID: carbon
      PUBSUB_HOST: pubsub.carbon.local
      PUBSUB_PORT: 80
    ports:
      - "40007:80"
  selenium.carbon.local:
    image: selenium/hub:3.13.0-argon
    ports:
      - "40004:4444"
    environment:
      GRID_BROWSER_TIMEOUT: 30
  chrome_node:
    image: selenium/node-chrome:3.13.0-argon
    depends_on:
      - selenium.carbon.local
    environment:
      HUB_HOST: selenium.carbon.local
      HUB_PORT: 4444
  firefox_node:
    image: selenium/node-firefox:3.13.0-argon
    depends_on:
      - selenium.carbon.local
    environment:
      HUB_HOST: selenium.carbon.local
      HUB_PORT: 4444
  scdf.carbon.local:
    build:
      context: ../carbon-crawler-scdf
      args:
        JAR_FILE: ./build/libs/carbon-crawler-scdf-0.1.0-SNAPSHOT.jar
    volumes:
      # making dataflow be able to access host's maven repository via maven:// schema
      - ~/.m2:/root/.m2
    ports:
      - "40008:8080"
    environment:
      - CARBON_API_CONFIG_HOST=config.carbon.local
      - CARBON_API_CONFIG_PORT=80
      - spring.cloud.skipper.client.serverUri=http://skipper:7577/api
      - spring.cloud.dataflow.applicationProperties.stream.spring.profiles.active=dev-internal
      - spring.cloud.dataflow.applicationProperties.logging.level.org.springframework.cloud.gcp.core.DefaultCredentialsProvider.=DEBUG
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.config.uri=http://config.carbon.local:80
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.config.failFast=true
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.gcp.pubsub.emulatorHost=pubsub.carbon.local:80
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.gcp.pubsub.projectId=carbon
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.bindings.applicationMetrics.destination=metrics
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.metrics.meterFilter=spring.integration.*
    depends_on:
      - config.carbon.local
  skipper:
    image: springcloud/spring-cloud-skipper-server:2.0.0.M1
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "7577:7577"
      - "9000-9010:9000-9010"
