spring:
  output.ansi.enabled: always
  cloud:
    stream:
      bindings:
        input:
          destination: crawl.target
          contentType: application/json
          group: g.crawl.target
      kafka:
        binder:
          brokers:
          - pause:9092

trigger:
  maxMessage: 1
  timeUnit: seconds
  fixedDelay: 1
  initialDelay: 0

rdb:
  main:
    url: jdbc:mysql://pause:43306/crawler_definition
    username: carbon
    password: carbonpw
    option:
      useSSL: false

logging.level.: info
