spring:
  output.ansi.enabled: detect
  cloud.gcp.pubsub:
    emulatorHost: pubsub.carbon.local:40007
    projectId: carbon
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - logfile

carbon.cloud.rdb.schema.crawlerdb.option:
  useSSL: false
